# Generated by Django 5.2.13 on 2026-04-18 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ Inquiry',
                'verbose_name_plural': 'FAQ Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Frequently Asked Questions', max_length=255)),
                ('seller_form_title', models.CharField(default='Contact Sellers', max_length=255)),
                ('seller_name', models.CharField(default='Growl Real Estate Seller', max_length=255)),
                ('seller_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('seller_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('seller_image', models.ImageField(blank=True, null=True, upload_to='faq/seller/')),
                ('ad_image', models.ImageField(blank=True, null=True, upload_to='faq/ad/')),
                ('ad_logo', models.ImageField(blank=True, null=True, upload_to='faq/ad/logo/')),
                ('ad_title', models.CharField(default='We can help you find a local real estate agent', max_length=255)),
                ('ad_description', models.TextField(blank=True, default='Connect with a trusted agent who knows the market inside out - whether you’re buying or selling.', null=True)),
                ('ad_button_text', models.CharField(default='Connect with an agent', max_length=100)),
                ('ad_button_link', models.CharField(blank=True, default='#', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ Page Setting',
                'verbose_name_plural': 'FAQ Page Settings',
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='faq.faqcategory')),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
