# Generated by Django 5.2.13 on 2026-04-20 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('source_manager', 'Source Manager')], max_length=20)),
                ('otp', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'OTP Request',
                'verbose_name_plural': 'OTP Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLoginProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('source_manager', 'Source Manager')], default='customer', max_length=20)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Login Profile',
                'verbose_name_plural': 'User Login Profiles',
            },
        ),
    ]
