# Generated by Django 5.2.13 on 2026-04-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userloginprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('source_manager', 'Source Manager')], default='customer', max_length=20),
        ),
    ]
