# Generated by Django 5.2.13 on 2026-06-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='keywords',
            field=models.TextField(blank=True, help_text='Add comma separated keywords, for example: Sales, Real Estate, CRM'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='preferred_skills',
            field=models.TextField(blank=True),
        ),
    ]
