# Generated by Django 5.2.13 on 2026-04-13 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration', models.CharField(default='month', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('listing_limit', models.PositiveIntegerField(default=50)),
                ('support_24_7', models.BooleanField(default=True)),
                ('quick_access', models.BooleanField(default=True)),
                ('auto_refresh_ads', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('full_address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('neighborhood', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('map_embed_url', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit_price', models.CharField(blank=True, default='', max_length=50)),
                ('before_price_label', models.CharField(blank=True, default='', max_length=100)),
                ('after_price_label', models.CharField(blank=True, default='', max_length=100)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('studio', 'Studio'), ('office', 'Office')], default='apartment', max_length=30)),
                ('property_status', models.CharField(choices=[('for-rent', 'For Rent'), ('for-sale', 'For Sale')], default='for-sale', max_length=30)),
                ('property_label', models.CharField(choices=[('new-listing', 'New Listing'), ('open-house', 'Open House'), ('featured', 'Featured')], default='new-listing', max_length=30)),
                ('post_status', models.CharField(choices=[('publish', 'Publish'), ('pending', 'Pending'), ('hidden', 'Hidden'), ('sold', 'Sold')], default='publish', max_length=20)),
                ('size_sqft', models.PositiveIntegerField(default=0)),
                ('land_area_sqft', models.PositiveIntegerField(default=0)),
                ('property_code', models.CharField(max_length=100, unique=True)),
                ('rooms', models.PositiveIntegerField(default=0)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('garages', models.PositiveIntegerField(default=0)),
                ('garages_size_sqft', models.PositiveIntegerField(default=0)),
                ('year_built', models.PositiveIntegerField(default=2024)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('virtual_tour_type', models.CharField(blank=True, default='', max_length=50)),
                ('virtual_tour_embed_code', models.TextField(blank=True, default='')),
                ('video_url', models.TextField(blank=True, default='')),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaveSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('email', models.EmailField(max_length=254)),
                ('published_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.CharField(blank=True, default='', max_length=255)),
                ('office_number', models.CharField(blank=True, default='', max_length=50)),
                ('office_address', models.CharField(blank=True, default='', max_length=255)),
                ('job', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('facebook', models.CharField(blank=True, default='#', max_length=255)),
                ('twitter', models.CharField(blank=True, default='#', max_length=255)),
                ('linkedin', models.CharField(blank=True, default='#', max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/avatar/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='profile/poster/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(blank=True, default='', max_length=100)),
                ('floor_price', models.CharField(blank=True, default='', max_length=100)),
                ('price_postfix', models.CharField(blank=True, default='', max_length=50)),
                ('floor_size', models.CharField(blank=True, default='', max_length=100)),
                ('size_postfix', models.CharField(blank=True, default='', max_length=50)),
                ('bedrooms', models.CharField(blank=True, default='', max_length=20)),
                ('bathrooms', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('floor_image', models.ImageField(blank=True, null=True, upload_to='properties/floorplans/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='admindashboard.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admindashboard.property')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_avatar', models.ImageField(blank=True, null=True, upload_to='reviews/avatar/')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='admindashboard.property')),
            ],
        ),
    ]
