# Generated by Django 5.2.13 on 2026-04-22 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0005_customersearchhistory_customervisitbooking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviter_name', models.CharField(max_length=120)),
                ('inviter_phone', models.CharField(max_length=30)),
                ('invitee_name', models.CharField(max_length=120)),
                ('invitee_phone', models.CharField(max_length=30)),
                ('invitee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relation', models.CharField(choices=[('friend', 'Friend'), ('family', 'Family'), ('colleague', 'Colleague'), ('relative', 'Relative'), ('other', 'Other')], max_length=30)),
                ('referral_type', models.CharField(choices=[('project', 'Project'), ('location', 'Location')], max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_referrals', to='admindashboard.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
