# Generated by Django 5.2.13 on 2026-05-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0006_customerreferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, null=True, unique=True),
        ),
    ]
