# Generated by Django 5.2.13 on 2026-05-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0007_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='availability_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='compliance_docs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='is_gated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='marketing_consent_text',
            field=models.TextField(blank=True, default='I agree to receive property updates and marketing communication.'),
        ),
        migrations.AddField(
            model_name='property',
            name='payment_schedule',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='property',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rera_disclaimer',
            field=models.TextField(blank=True, default='Project registered under MahaRERA. Login to view complete compliance details.'),
        ),
        migrations.AddField(
            model_name='property',
            name='rera_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='schema_type',
            field=models.CharField(blank=True, default='RealEstateListing', max_length=80),
        ),
        migrations.AddField(
            model_name='property',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='property',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='show_brochure_publicly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='show_floor_plan_publicly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='show_price_publicly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='show_seller_publicly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
    ]
