# Generated by Django 5.2.13 on 2026-05-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Example: home, listing, cities, developers, faq, blog, contact, about', max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('path', models.CharField(help_text='Example: /, /cities, /contact', max_length=255)),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('starts_with', 'Starts With'), ('custom_blog', 'Custom Blog Match')], default='exact', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Header Menu',
                'verbose_name_plural': 'Header Menus',
                'ordering': ['order', 'id'],
            },
        ),
    ]
