# Generated by Django 5.2.13 on 2026-05-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headermenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headermenu',
            name='key',
            field=models.CharField(blank=True, help_text='Example: home, listing, cities, developers, faq, blog, contact, about', max_length=100, null=True, unique=True),
        ),
    ]
