# Generated by Django 5.2.13 on 2026-06-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='interest',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=20),
        ),
    ]
