# Generated by Django 5.2.13 on 2026-04-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Contact Info',
                'verbose_name_plural': 'About Contact Info',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aboutus/gallery/')),
                ('row_number', models.PositiveIntegerField(choices=[(1, 'Row 1'), (2, 'Row 2'), (3, 'Row 3')], default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Gallery Image',
                'verbose_name_plural': 'About Gallery Images',
                'ordering': ['row_number', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutGallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Gallery', max_length=255)),
                ('title', models.CharField(default='Our Real Estate Showcase', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Gallery Section',
                'verbose_name_plural': 'About Gallery Section',
            },
        ),
        migrations.CreateModel(
            name='AboutHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='About Growl Real Estate', max_length=255)),
                ('title', models.CharField(default='Mumbai’s Trusted Property Partners', max_length=255)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='aboutus/hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Hero Section',
                'verbose_name_plural': 'About Hero Section',
            },
        ),
        migrations.CreateModel(
            name='AboutLocationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Serving Locations', max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Location Info',
                'verbose_name_plural': 'About Location Info',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Resource Item',
                'verbose_name_plural': 'About Resource Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutResourceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Our Resources', max_length=255)),
                ('title', models.CharField(default='Everything You Need for a Smooth Property Journey', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='aboutus/resources/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Resource Section',
                'verbose_name_plural': 'About Resource Section',
            },
        ),
        migrations.CreateModel(
            name='AboutTeamIntroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Our Team', max_length=255)),
                ('title', models.CharField(default='A Dedicated Team That Truly Cares', max_length=255)),
                ('paragraph_1', models.TextField(blank=True, null=True)),
                ('paragraph_2', models.TextField(blank=True, null=True)),
                ('paragraph_3', models.TextField(blank=True, null=True)),
                ('paragraph_4', models.TextField(blank=True, null=True)),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='aboutus/team_intro/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Team Intro Section',
                'verbose_name_plural': 'About Team Intro Section',
            },
        ),
        migrations.CreateModel(
            name='AboutTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('designation', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='aboutus/team_members/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Team Member',
                'verbose_name_plural': 'About Team Members',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutTeamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Team Members', max_length=255)),
                ('title', models.CharField(default='Meet Our Experts', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Team Section',
                'verbose_name_plural': 'About Team Section',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Card',
                'verbose_name_plural': 'Why Choose Us Cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Why Choose Us', max_length=255)),
                ('title', models.CharField(default='Built on Trust, Driven by Results', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Section',
                'verbose_name_plural': 'Why Choose Us Section',
            },
        ),
    ]
