# Generated by Django 5.2.13 on 2026-04-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_blog', '0002_alter_blogcategory_options_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('quote', 'Quote'), ('html', 'HTML'), ('image', 'Image'), ('video', 'Video')], default='paragraph', max_length=20),
        ),
    ]
