# Generated by Django 5.2.13 on 2026-04-24 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('widget_key', models.CharField(max_length=120, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#FF7A1A', max_length=20)),
                ('secondary_color', models.CharField(default='#0B1320', max_length=20)),
                ('bot_name', models.CharField(default='Property AI Assistant', max_length=120)),
                ('welcome_message', models.TextField(default='Hi! Main aapki property search me help kar sakta hoon. Aap city, budget, BHK ya project name puch sakte ho.')),
                ('fallback_message', models.TextField(default='Mujhe exact matching project nahi mila, lekin main aapko latest available projects suggest kar raha hoon.')),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('show_latest_projects_on_random_question', models.BooleanField(default=True)),
                ('latest_project_limit', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=180)),
                ('visitor_name', models.CharField(blank=True, max_length=120, null=True)),
                ('visitor_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('visitor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='aichatbot.chatbottenant')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('properties_payload', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='aichatbot.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='ChatLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('requirement', models.TextField(blank=True, null=True)),
                ('property_id', models.PositiveIntegerField(blank=True, null=True)),
                ('property_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=150, null=True)),
                ('seller_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('seller_phone', models.CharField(blank=True, max_length=40, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_email_sent_to_admin', models.BooleanField(default=False)),
                ('is_email_sent_to_seller', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='aichatbot.chatbottenant')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='aichatbot.chatsession')),
            ],
        ),
    ]
