# Generated by Django 5.2.13 on 2026-04-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbottenant',
            name='property_api_auth_type',
            field=models.CharField(blank=True, choices=[('none', 'No Auth'), ('bearer', 'Bearer Token'), ('api_key', 'API Key Header')], default='none', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chatbottenant',
            name='property_api_key_header',
            field=models.CharField(blank=True, default='Authorization', help_text='Example: Authorization or X-API-Key', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatbottenant',
            name='property_api_token',
            field=models.TextField(blank=True, help_text='Bearer token or API key if required', null=True),
        ),
        migrations.AddField(
            model_name='chatbottenant',
            name='property_api_url',
            field=models.URLField(blank=True, help_text='Tenant specific property/project API URL', null=True),
        ),
    ]
