# Generated by Django 5.2.13 on 2026-04-25 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichatbot', '0002_chatbottenant_property_api_auth_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbottenant',
            name='auto_sync_property_cache',
            field=models.BooleanField(default=True, help_text='If true, chatbot will save tenant API property data in JSON cache.'),
        ),
        migrations.AlterField(
            model_name='chatbottenant',
            name='property_api_key_header',
            field=models.CharField(blank=True, default='Authorization', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatbottenant',
            name='property_api_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatlead',
            name='property_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ChatbotPropertyCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('price_text', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('flattened_text', models.TextField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_cache', to='aichatbot.chatbottenant')),
            ],
            options={
                'unique_together': {('tenant', 'external_id')},
            },
        ),
    ]
