# Generated by Django 5.2.13 on 2026-04-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField()),
                ('avatar', models.URLField(blank=True, default='')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('width', models.PositiveIntegerField(default=120)),
                ('height', models.PositiveIntegerField(default=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-id'],
            },
        ),
    ]
