# Generated by Django 5.2.13 on 2026-06-13 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.FileField(blank=True, help_text='Optional notification image.', null=True, upload_to='notifications/images/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='video',
            field=models.FileField(blank=True, help_text='Optional notification video.', null=True, upload_to='notifications/videos/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_notifications', through='notifications.UserNotification', to=settings.AUTH_USER_MODEL),
        ),
    ]
