# Generated by Django 5.2.13 on 2026-06-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_image_notification_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
